---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb-deployment
  namespace: mhouas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: mah5000/site_web:3.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service.mhouas.svc.cluster.local:27017/"
        - name: MONGO_DB_NAME
          value: "flask_db"
        - name: MONGO_COLLECTION_NAME
          value: "requests"     
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: mhouas
spec:
  type: ClusterIP
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
